<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>f9a127b0-d024-4f5b-9dd3-6bf38eda677b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults" Version="4.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Movies.Api\Movies.Api.csproj"/>
        <ProjectReference Include="..\..\Movies.Application\Movies.Application.csproj"/>
        <ProjectReference Include="..\..\Movies.Contracts\Movies.Contracts.csproj"/>
    </ItemGroup>

</Project>
